apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
spec:
  dnsNames:
    - nextcloud.myapp.com
  secretName: nextcloud-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
