kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud 
  namespace: default
  labels:
    app: nextcloud 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud 
        image: nextcloud:27.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-data 
          mountPath: /var/www/html/data
        - name: nextcloud-config
          mountPath: /var/www/html/config
        - name: nextcloud-apps
          mountPath: /var/www/html/custom_apps
        - name: nextcloud-html
          mountPath: /var/www/html
        env:
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: TRUSTED_PROXIES
          value: "nextcloud"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          value: "nextcloud"
        - name: MYSQL_PASSWORD
          value: "changeme"
        - name: MYSQL_HOST
          value: "127.0.0.1"
      - name: mariadb 
        image: mariadb
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-nc
          mountPath: /var/lib/mysql
        args:
        - --innodb-read-only-compressed=OFF
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "changeme"
        - name: MARIADB_DATABASE
          value: "nextcloud"
        - name: MARIADB_USER
          value: "nextcloud"
        - name: MARIADB_PASSWORD
          value: "changeme"
      - name: redis 
        image: redis
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "127.0.0.1"
      volumes:
      - name: nextcloud-data 
        persistentVolumeClaim:
          claimName: nextcloud-data 
      - name: nextcloud-config
        persistentVolumeClaim:
            claimName: nextcloud-config
      - name: nextcloud-apps
        persistentVolumeClaim:
            claimName: nextcloud-apps
      - name: nextcloud-html
        persistentVolumeClaim:
            claimName: nextcloud-html
      - name: mariadb-nc
        persistentVolumeClaim:
            claimName: mariadb-nc


